name: nature_tracker
description: "Valerio Blog App Project"
publish_to: "none"
version: 0.1.0

environment:
 sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  volume_controller: ^2.0.2
  uuid: ^4.5.0 
  flutter_svg: ^2.0.7 
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2
  pedometer: ^4.0.2  
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  google_maps_flutter: ^2.0.1
  provider: ^6.1.2 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Icon_Black.png
    - assets/images/Logo_Black_NatureTracker_Double.png
    - assets/images/LogoHintergrundSchwarz-04.png
    - assets/images/Icon_White.png
    - assets/images/Logo_Black_NatureTracker_Long.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon_Black.png" # Path to your icon file
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icons
  adaptive_icon_foreground: "assets/images/Icon_Black.png" # Path to foreground icon for adaptive icons