name: nature_tracker
description: "Valerio Blog App Project"
publish_to: "none"
version: 0.1.0

environment:
 sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  volume_controller: ^2.0.2
  uuid: ^3.0.6 # For unique IDs for bins
  flutter_svg: ^2.0.7 # Add the flutter_svg package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_M.svg
    - assets/images/LogoSchwarz-04.png
    - assets/images/LogoHintergrundSchwarz-04.png
    - assets/images/background-06.png
    - assets/images/header.png
